Blog app - integration specs for views and fix n+1 problems
AnicetFantomas/Blog_app pull request #8
Opened 2022-07-26 14:12 UTC by AnicetFantomas

In this pull request we performed :

- Write integration tests with Capybara gem.
- Secure app from n+1 problems.

2022-07-26 15:52 UTC, ShadyShawkat requested changes
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-26 15:52 UTC, ShadyShawkat commented on app/models/post.rb
> +    comments.includes(:user).order(created_at: :desc).limit(5)
- [ ] Kindly make sure to solve the N+1 problem from the posts controller and the user controller not in the models, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=Make%20sure%20that%20the%20N%2B1%20problem%20is%20solved%20when%20fetching%20all%20posts%20and%20their%20comments%20for%20a%20user.) requirement.

2022-07-26 15:52 UTC, ShadyShawkat commented on spec/integration/post_show_spec.rb
> +      @first_user.save!
- [ ] Please make sure that the tests run successfully and pass. Currently, there're tests that fail, check the attached below.
![image](https://user-images.githubusercontent.com/62290545/181051796-6e42400b-d1fd-4cc7-935a-a371100cc1dc.png)

2022-07-27 10:10 UTC, dasileker requested changes
### **Hi @AnicetFantomas,** 

### **Great work on making the changes 👏** 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## **Suggested changes**
_Check the comments under the review._

- **Nice job my friend, but there are still some tests that are failing so please fix them I attached a screenshot to help you.**

![Capture d’écran 2022-07-27 110618](https://user-images.githubusercontent.com/61562626/181222142-9d61d6c2-749c-477a-a8f9-9c8b060dc720.png)
![Capture d’écran 2022-07-27 110651](https://user-images.githubusercontent.com/61562626/181222148-b2da3dd0-d3b3-45d6-9959-8f7cd0c2344c.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-27 13:35 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @AnicetFantomas, @YannickZahinda and @white3d,

✔️ All integration tests are passing

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

## NB: You should consider using the default `.gitgnore` file that comes with the `rails new` command to avoid committing unnecessary files to your repository. It is set up to ignore certain files in the `tmp` directory while not ignoring the directory completely.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 18:27 UTC, Davidosky007 approved these changes
Hi @AnicetFantomas 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 20:10 UTC, merged