Blog app: add devise
AnicetFantomas/Blog_app pull request #9
Opened 2022-07-29 16:26 UTC by AnicetFantomas

In this pull request we perforned :

- Build a web app that requires the user to log in.
- Use devise gem for authentication.

2022-07-29 17:05 UTC, Danieldotcomcoder requested changes
Hello @AnicetFantomas , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- Clear and nice code ✔✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-29 17:05 UTC, Danieldotcomcoder commented on app/views/devise/registrations/new.html.erb
> +<% end %>
when I tried to sign up I got an error and no new user was created , Kindly fix this issue 😄 
Probably because you didn't add the name to the sign up page so its submitting an empty string for the name parameter 👍 

here is the error : 
![image](https://user-images.githubusercontent.com/87448628/181808097-c397cf30-83be-4b9a-a7e6-89ebbdd7248c.png)

2022-07-29 17:05 UTC, Danieldotcomcoder commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
In order for email confirmation to work , you need to add :confirmable to the devise here, Kindly fix this issue 😄 👍

2022-07-30 09:15 UTC, DeliceLydia approved these changes
## Hi @AnicetFantomas, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 18:33 UTC, merged